# Generated by Django 4.0.5 on 2022-09-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskday',
            name='opis',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
