# Generated by Django 4.0.5 on 2022-09-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_day', '0003_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskday',
            name='opis',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
